name: Deploy React App to GitHub Pages

on:
  push:
    branches:
      - deploy
    
jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: 1. Checkout Repository
        uses: actions/checkout@v3

      - name: 2. Setup Node.js with Dependency Caching
        uses: actions/setup-node@v3
        with:
          node-version: '20.11.1'
          cache: 'npm'

      - name: 3. Install Dependencies
        run: npm ci

      - name: 4. Build Static Files
        run: npm run build

      - name: 5. Create CNAME for Custom Domain
        run: echo "dhriti.mind-empowered.org" > dist/CNAME

      - name: 6. Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
